name:                kolaboro-be
version:             0.1.0.0
github:              "ilhamelhamdi/kolaboro-be"
license:             BSD-3-Clause
author:              "Ilham Abdillah Alhamdi"
maintainer:          "ilham.abdillah.alhamdi@gmail.com"
copyright:           "2024 Ilham Abdillah Alhamdi"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ilhamelhamdi/kolaboro-be#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant
- servant-server
- servant-auth
- servant-auth-server
- wai
- warp
- time
- persistent
- persistent-postgresql
- persistent-template
- monad-logger
- resourcet
- text
- transformers
- resource-pool
- mtl
- postgresql-simple
- bytestring
- jose
- lens
- servant-websockets
- websockets
- containers
- stm
- wai-cors
- http-types
- wai-logger
- wai-extra


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  kolaboro-be-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - kolaboro-be

tests:
  kolaboro-be-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - kolaboro-be
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
    - time
